aprendeii/urls.py
from django.contrib import admin
from django.urls import path, include
import studentsmanager.views as studentsmanager_views
#import authoringtool.views as authoringtool_views

# API
#from rest_framework import routers
#from rest_framework.urlpatterns import format_suffix_patterns

#router = routers.DefaultRouter()
#router.register(r'units', mc_views.UnitViewSet)
#router.register(r'users', usersmanager_views.UserViewSet)
# router.register('^units/{unit}/$', mc_views.unit_detail, basename="unit-detail")

urlpatterns = [
    path('', studentsmanager_views.LoginView.as_view(), name='login'),
    #path('api/', include(router.urls)),
    #path('units/', authoringtool_views.UnitList.as_view()),
    #path('units/<str:unit>/', authoringtool_views.UnitDetail.as_view()),
    path('authoringtool/', include('authoringtool.urls')),
    path('admin/', admin.site.urls),
    path('user_page/', studentsmanager_views.HomeView.as_view(), name='user_page'),
    path('accounts/', include('studentsmanager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usersmanager/', include('usersmanager.urls')),
    path('ebisu/', include('ebisu_api.urls')),
    #path('authoringtool', authoringtool_views.microcontent, name='authoringtool'),
]

authoringtool/urls.py
from django.urls import path

from . import views
from studentsmanager import views as user_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'authoringtool'

urlpatterns = [
    path('', user_views.HomeView.as_view(), name='menu'),
    path('newMicroContent/<int:preq>/<int:media>/<int:postq>', views.MicroContentCreationView.as_view(), name='microcontent_creation'), 
    path('microcontent_search/', views.MicroContentSearchView.as_view(), name='microcontent_search'),
    path('createSelection/', views.CreateSelectionView.as_view(), name='create_selection'),
    path('store/<int:pre_questions>/<int:post_questions>/', views.StoreView.as_view(), name='store'),
    path('delete/<int:id_metadata>/', views.DeleteView.as_view(), name='delete'),
    path('preview/<int:id_metadata>/', views.PreviewView.as_view(), name='preview'),
    path('edit_microcontent/<int:id_metadata>/', views.EditView.as_view(), name='edit_microcontent'),
    path('playlist_creation/', views.CreatePlaylistView.as_view(), name='playlist_creation'),
    path('playlist_search/', views.PlaylistSearchView.as_view(), name='playlist_search'),
    path('edit_playlist/<int:id_playlist>/', views.EditPlaylistView.as_view(), name='edit_playlist'),
    path('preview_playlist/<int:id_playlist>/', views.PreviewPlaylistView.as_view(), name='preview_playlist'),
    path('preview_keyword/<int:id_playlist>/<str:keyword>', views.PreviewKeywordView.as_view(), name='preview_keyword'),
    path('delete_playlist/<int:id_playlist>/', views.DeletePlaylistView.as_view(), name='delete_playlist'),
    path('duplicate_microcontent/<int:id_metadata>/<user>/', views.DuplicateMicrocontentView.as_view(), name='duplicate_microcontent'),
    path('duplicate_playlist/<int:id_playlist>/', views.DuplicatePlaylistView.as_view(), name='duplicate_playlist'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usersmanager/urls.py
from django.urls import path

from . import views

app_name = 'usersmanager'

urlpatterns = [
    path('user_data/', views.UserDataView.as_view(), name='user_data'),
    path('edit_user_data/<int:id>', views.EditUserDataView.as_view(), name='edit_user_data'),
    path('password_change/', views.change_password, name='password_change'),
    path('login/', views.LoginView.as_view(), name='login_as_teacher'),
    path('signup/', views.SignUp.as_view(), name='signup_as_teacher'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('students_list_pl/<playlist_id>', views.StudentsListViewPlaylist.as_view(), name='students_list_playlist'),
    path('students_list/<playlist_id>/<mc_id>', views.StudentsListView.as_view(), name='students_list'),
    path('export_all/<user>/<playlist_id>', views.export_all, name='export_all'),
    path('view_traces_all/<user>/<playlist_id>', views.ViewGeneralTraces.as_view(), name='view_all_traces'),
    path('export/<user>/<mc_id>', views.export, name='export'),
    path('view_comments/', views.viewCommentsView.as_view(), name='viewcomments'),
    path('view_comments/<user>', views.viewCommentsperStudentView.as_view(), name='view_comments_per_student'),
    path('view_traces/<user>/<mc_id>', views.ViewTracesView.as_view(), name='view_traces')
]

authoringtool/views.py
from datetime import time
from typing import List
from .models import Media, MetaData, Question, MicroContent, Prequestionnaire, Postquestionnaire, SortedMicrocontent, Playlist, Keyword
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.utils import timezone
from django.utils.datastructures import MultiValueDictKeyError
import sqlite3
import operator
from django.conf import settings

NUMBER_PARAGRAPHS = 1
NUMBER_CHOICES = 3
NUMBER_QUESTIONS = 1

#LISTADO DE MICROCONTENIDOS
class MicroContentSearchView(generic.DetailView):
    template_name = 'authoringtool/microcontent_list.html'

    def get(self, request, *args, **kwargs):

        microcontents = MicroContent.objects.filter(show='yes').order_by('-metadata_id')
        
        return render(request, 'authoringtool/microcontent_list.html', {"microcontents": microcontents})

#ELECCION DE TIPO DE MICROCONTENIDO
class CreateSelectionView(generic.TemplateView):

    def get(self, request, *args, **kwargs):
        return render(request, 'authoringtool/create_selection.html')

#CREACION DE MICROCONTENIDO
class MicroContentCreationView(generic.CreateView):
    success_url = reverse_lazy('auth_tool:index')
    template_name = 'authoringtool/create.html'

    def get(self, request, *args, **kwargs):
        return render(request, 'authoringtool/create.html', {'paragraphs': ' ' * NUMBER_PARAGRAPHS,
                                                             'preQuestionnaire': kwargs['preq'],
                                                             'media': kwargs['media'],
                                                             'postQuestionnaire': kwargs['postq'],
                                                             'numberQuestions': NUMBER_QUESTIONS,
                                                             'numberChoices': ' ' * NUMBER_CHOICES})

#GUARDAR MICROCONTENIDO
class StoreView(generic.TemplateView):
    template_name = 'authoringtool/store.html'

    def post(self, request, *args, **kwargs):
        # prequestionnaire
        prequestionnaire = Prequestionnaire()
        prequestionnaire.save()

        # for of number questions size
        for q in range(int(kwargs['pre_questions'])):
            q = q+1
            try:
                # statement of the question
                question_statement = request.POST['prequestion' + str(q)]
                first_choice = request.POST['prechoice' + str(q) + "_" + str(1)]
                second_choice = request.POST['prechoice' + str(q) + "_" + str(2)]
                third_choice = request.POST['prechoice' + str(q) + "_" + str(3)]
                correct_answer = request.POST[request.POST['preanswer' + str(q)]]
                explanation = request.POST['preexplanation' + str(q)]
                order = request.POST['preorder' + str(q)]

                question = Question(question=question_statement,
                                    first_choice=first_choice,
                                    second_choice=second_choice,
                                    third_choice=third_choice,
                                    correct_answer=correct_answer,
                                    explanation=explanation,
                                    order_in_questionnaire=order)
                question.save()
                prequestionnaire.question.add(question)
            except MultiValueDictKeyError:
                pass

        # postquestionnaire
        postquestionnaire = Postquestionnaire()
        postquestionnaire.save()

        # for of number questions size
        for q in range(int(kwargs['post_questions'])):
            q = q+1
            try:
                # statement of the question
                question_statement = request.POST['postquestion' + str(q)]
                first_choice = request.POST['postchoice' +
                                            str(q) + "_" + str(1)]
                second_choice = request.POST['postchoice' +
                                             str(q) + "_" + str(2)]
                third_choice = request.POST['postchoice' +
                                            str(q) + "_" + str(3)]
                correct_answer = request.POST[request.POST['postanswer' +
                                                           str(q)]]
                explanation = request.POST['postexplanation' + str(q)]
                order = request.POST['postorder' + str(q)]

                question = Question(question=question_statement,
                                    first_choice=first_choice,
                                    second_choice=second_choice,
                                    third_choice=third_choice,
                                    correct_answer=correct_answer,
                                    explanation=explanation,
                                    order_in_questionnaire=order)
                question.save()
                postquestionnaire.question.add(question)
            except MultiValueDictKeyError as err:
                print(err)
                pass

        name = request.POST['title']

        level = request.POST['level']

        unit = 'notused'

        description = request.POST['description']

        keywords = request.POST['keywords']

        metadata = MetaData(title=request.POST['title'], author=request.POST['author'], pub_date=timezone.now(), last_modification=timezone.now())
        metadata.save()

        if 'mediaType' in request.POST:
            if request.POST['mediaType'] == "video":
                if request.POST['upload_form'] == "from_existing_file":
                    media = Media(type=request.POST['mediaType'], 
                                url=Media.buildURL(request), 
                                upload_form=request.POST['upload_form'],
                                mediaFile=request.FILES['videoFile'],
                                text=request.POST['text'])
                else:
                    media = Media(type=request.POST['mediaType'], 
                                url=request.POST['videoURL'], 
                                upload_form=request.POST['upload_form'],
                                mediaFile=None,
                                text=request.POST['text'])
            
            if request.POST['mediaType'] == "audio":
                media = Media(type=request.POST['mediaType'], 
                                url=Media.buildURL(request), 
                                upload_form=request.POST['upload_form'],
                                mediaFile=request.FILES['audioFile'],
                                text=request.POST['text'])

            if request.POST['mediaType'] == "image":
                media = Media(type=request.POST['mediaType'], 
                                url=Media.buildURL(request), 
                                upload_form=request.POST['upload_form'],
                                mediaFile=request.FILES['imageFile'],
                                text=request.POST['text'])                    

            if request.POST['mediaType'] == "text":
                media = Media(type=request.POST['mediaType'], 
                                url=None,
                                upload_form=None,
                                mediaFile=None,
                                text=request.POST['text'])

            media.id_telegram = request.POST['id_telegram']
            media.save()

            content = MicroContent(name=name, level=level, playlist=unit, description=description, keywords=keywords, metadata=metadata, media=media,
                                   pre_questionaire=prequestionnaire, post_questionaire=postquestionnaire, show='yes')
        else:
            content = MicroContent(
                name=name, level=level, playlist=unit, description=description, keywords=keywords, metadata=metadata, pre_questionaire=prequestionnaire, post_questionaire=postquestionnaire, show='yes')
        content.save()

        mc = MicroContent.objects.filter(name=name, show='yes').get()
        mc_id = mc.metadata_id

        return render(request, 'authoringtool/store.html', {'mc_id': mc_id})

#DUPLICAR MICROCONTENIDO
class DuplicateMicrocontentView(generic.TemplateView):
    template_name = 'authoringtool/duplicate_microcontent.html'

    def get(self, request, *args, **kwargs):
        id_metadata = int(kwargs['id_metadata'])
        mc = MicroContent.objects.filter(metadata_id=id_metadata).get()

        name = mc.name + "- copy"

        keywords = mc.keywords
        description = mc.description

        user = kwargs['user']

        try:
            media = Media(type=mc.media.type, upload_form=mc.media.upload_form, url=mc.media.url, mediaFile=mc.media.mediaFile, text=mc.media.text, id_telegram=mc.media.id_telegram)
            media.save()
        except:
            pass
        

        metadata = MetaData(title=name, author=user, pub_date=timezone.now(), last_modification=timezone.now())
        metadata.save()

        #Prequestionnaire
        prequestionnaire = Prequestionnaire()
        prequestionnaire.save()

        pre_questions = mc.pre_questionaire.question.all()
        pre_questions = sorted(pre_questions, key=operator.attrgetter('order_in_questionnaire'))

        for preq in pre_questions:
            question = Question(question=preq.question, first_choice=preq.first_choice, second_choice=preq.second_choice, third_choice=preq.third_choice, correct_answer=preq.correct_answer, explanation=preq.explanation)
            question.save()
            prequestionnaire.question.add(question)

        #Postquestionnaire
        postquestionnaire = Postquestionnaire()
        postquestionnaire.save()

        post_questions = mc.post_questionaire.question.all()
        post_questions = sorted(post_questions, key=operator.attrgetter('order_in_questionnaire'))

authoringtool/templates/authoringtool/create_selection.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Create selection</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'create_selection_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
</head>
<body>
    <div class="user_options">
        <h1 class="top-content"><a id="home_button" class="po home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>
        <div class="cards">
            <div class="single-grid">
                <div class="grid-item single_media">
                    <i class="fa fa-video-camera" aria-hidden="true"></i>
                    <h1>Single media</h1>
                    <p>
                    A single multimedia file for students to see and reflect
                    </p>
                    <a href="{% url 'authoringtool:microcontent_creation' 0 1 0 %}" class="btn">Create</a>
                </div>
                <div class="grid-item single-quest">
                    <i class="fa fa-question-circle" aria-hidden="true"></i>
                    <h1>Single Questionnaire</h1>
                    <p>
                    A single questionnaire to assess students' knowledge
                    </p>
                    <a href="{% url 'authoringtool:microcontent_creation' 0 0 1 %}" class="btn">Create</a>
                </div>
            </div>
        </div>
    </div>
    <div class="user_options">
      <div class="cards">
        <div class="lower_grid">
          <div class="grid-item pre_quest">
            <i class="fa fa-question-circle" aria-hidden="true">  <i id="home" class="fa fa-video-camera" aria-hidden="true"></i></i>
            
            <h1>Pre Questionnaire</h1>
            <p>
              A multimedia file with a previous questionnaire to discover the previous knowledge of the students
            </p>
            <a href="{% url 'authoringtool:microcontent_creation' 1 1 0 %}" class="btn">Create</a>
          </div>

          <div class="grid-item post_quest">
            <i class="fa fa-video-camera" aria-hidden="true">  <i id="home" class="fa fa-question-circle" aria-hidden="true"></i></i>
            <h1>Post Questionnaire</h1>
            <p>
              A multimedia file followed by a questionnaire to evaluate what has been learned
            </p>
            <a href="{% url 'authoringtool:microcontent_creation' 0 1 1 %}" class="btn">Create</a>
          </div>

          <div class="grid-item pre_post_quest">
            <i class="fa fa-question-circle" aria-hidden="true">  <i id="home" class="fa fa-video-camera" aria-hidden="true"></i>  <i id="home" class="fa fa-question-circle" aria-hidden="true"></i></i>
            <h1>Pre&Post Questionnaire</h1>
            <p>
              Complete micro-content with a multimedia file and pre and post questionnaires
            </p>
            <a href="{% url 'authoringtool:microcontent_creation' 1 1 1 %}" class="btn">Create</a>
          </div>
        </div>
      </div>
    </div>
</body>

authoringtool/templates/authoringtool/duplicate_microcontent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Course deleted</title>
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'store_style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">

    <h1>Microcontent with ID {{ id_metadata }} has been duplicated</h1>
    <h1 class="top-content">
        <a id="view_button" class="po view" title="Preview Microcontent" href="{% url 'authoringtool:preview' mc_id %}">
        <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>&nbsp;&nbsp;
    
        <a id="edit_button" class="po edit" title="Edit Microcontent" href="{% url 'authoringtool:edit_microcontent' mc_id %}">
        <i id="edit" class="fa fa-pencil" aria-hidden="true"></i></a>&nbsp;&nbsp;

        <a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}">
        <i id="home" class="fa fa-home" aria-hidden="true"></i></a>&nbsp;&nbsp;

        <a id="duplicate_button" class="po duplicate" title="Duplicate Microcontent" href="{% url 'authoringtool:duplicate_microcontent' mc_id user.username %}">
        <i id="duplicate" class="fa fa-plus" aria-hidden="true"></i></a>&nbsp;&nbsp;

        <a id="delete_button" class="po delete" title="Delete Microcontent" href="{% url 'authoringtool:delete' mc_id %}">
        <i id="delete" class="fa fa-trash" aria-hidden="true"></i></a></h1>
    </h1>
    
</body>
</html>

authoringtool/templates/authoringtool/microcontent_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Microcontent list</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authoring_tool_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">
    
    <h1>Microcontent list</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>


    <br>

    <div class="table-wrapper">
        <table class="fl-table" id="myTable">
            <thead>
            <tr>
                <th onclick="sortTable(0)">Title</th>
                <th onclick="sortTable(1)">Author</th>
                <th onclick="sortTable(2)">Level</th>
                <th onclick="sortTable(3)">Keywords</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% for mc in microcontents %}
                    <tr>
                        <td>{{ mc.name }}</td>
                        <td>{{ mc.metadata.author }}</td>
                        <td>{{ mc.level }}</td>
                        <td>{{ mc.keywords }}</td>
                        <td>
                        {% csrf_token %}
                            <div class="table_button">
                                <a id="view_button" class="po view" title="Preview Microcontent" href="{% url 'authoringtool:preview' mc.metadata.id %}">
                                <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>

                                <a id="duplicate_button" class="po duplicate" title="Duplicate Microcontent" href="{% url 'authoringtool:duplicate_microcontent' mc.metadata.id user.username %}">
                                <i id="duplicate" class="fa fa-plus" aria-hidden="true"></i></a>

                                <a id="edit_button" class="po edit" title="Edit Microcontent" href="{% url 'authoringtool:edit_microcontent' mc.metadata.id %}">
                                <i id="edit" class="fa fa-pencil" aria-hidden="true"></i></a>

                                <a id="delete_button" class="po delete" title="Delete Microcontent" href="{% url 'authoringtool:delete' mc.metadata.id %}">
                                <i id="delete" class="fa fa-trash" aria-hidden="true"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            <tbody>
        </table>
    </div>
    <script>

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 0; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("td")[n];
                    y = rows[i + 1].getElementsByTagName("td")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerText.toLowerCase() > y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerText.toLowerCase() < y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
<body>

authoringtool/templates/authoringtool/playlist_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Courses list</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authoring_tool_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">
    <script>
        function seleccionar(sel, desel) {
            for (var i = 1; i < desel+1; i++) { 
                document.getElementById("option" + i).style.color = '#6f6cde';
                document.getElementById("option" + i).style.boxShadow = '-6px -6px 10px rgba(255, 255, 255, 0.8), 6px 6px 10px rgba(0, 0, 0, 0.2)';
            }
            document.getElementById("option" + sel).style.color = '#6BE579';
            document.getElementById("option" + sel).style.boxShadow = 'inset -4px -4px 8px rgba(255, 255, 255, 0.5), inset 8px 8px 16px rgba(0, 0, 0, 0.1)';
        }

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 0; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("td")[n];
                    y = rows[i + 1].getElementsByTagName("td")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerText.toLowerCase() > y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerText.toLowerCase() < y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
    <h1>Courses List</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>

    <br>

    <div class="table-wrapper">
        <table class="fl-table" id="myTable">
            <thead>
            <tr>
                <th onclick="sortTable(0)">Title</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% for list in playlists %}
                    <tr>
                        <td>{{ list.name }}</td>
                        <td>
                        {% csrf_token %}
                            <div class="table_button">
                                <a id="view_button" class="po view" title="View course" href="{% url 'authoringtool:preview_playlist' list.id %}">
                                <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>

                                <a id="duplicate_button" class="po duplicate" title="Duplicate Course" href="{% url 'authoringtool:duplicate_playlist' list.id %}">
                                <i id="duplicate" class="fa fa-plus" aria-hidden="true"></i></a>

                                <a id="edit_button" class="po edit" title="Edit course" href="{% url 'authoringtool:edit_playlist' list.id %}">
                                <i id="edit" class="fa fa-pencil" aria-hidden="true"></i></a>

                                <a id="delete_button" class="po delete" title="Delete course" href="{% url 'authoringtool:delete_playlist' list.id %}">
                                <i id="delete" class="fa fa-trash" aria-hidden="true"></i></a>

                                <a id="edit_button" class="po edit" title="View students" href="{% url 'usersmanager:students_list_playlist' list.id %}">
                                    <i id="edit" class="fa fa-user" aria-hidden="true"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            <tbody>
        </table>
    </div>
<body>