aprendeii/urls.py
from django.contrib import admin
from django.urls import path, include
import studentsmanager.views as studentsmanager_views
#import authoringtool.views as authoringtool_views

# API
#from rest_framework import routers
#from rest_framework.urlpatterns import format_suffix_patterns

#router = routers.DefaultRouter()
#router.register(r'units', mc_views.UnitViewSet)
#router.register(r'users', usersmanager_views.UserViewSet)
# router.register('^units/{unit}/$', mc_views.unit_detail, basename="unit-detail")

urlpatterns = [
    path('', studentsmanager_views.LoginView.as_view(), name='login'),
    #path('api/', include(router.urls)),
    #path('units/', authoringtool_views.UnitList.as_view()),
    #path('units/<str:unit>/', authoringtool_views.UnitDetail.as_view()),
    path('authoringtool/', include('authoringtool.urls')),
    path('admin/', admin.site.urls),
    path('user_page/', studentsmanager_views.HomeView.as_view(), name='user_page'),
    path('accounts/', include('studentsmanager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usersmanager/', include('usersmanager.urls')),
    path('ebisu/', include('ebisu_api.urls')),
    #path('authoringtool', authoringtool_views.microcontent, name='authoringtool'),
]

authoringtool/urls.py
from django.urls import path

from . import views
from studentsmanager import views as user_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'authoringtool'

urlpatterns = [
    path('', user_views.HomeView.as_view(), name='menu'),
    path('newMicroContent/<int:preq>/<int:media>/<int:postq>', views.MicroContentCreationView.as_view(), name='microcontent_creation'), 
    path('microcontent_search/', views.MicroContentSearchView.as_view(), name='microcontent_search'),
    path('createSelection/', views.CreateSelectionView.as_view(), name='create_selection'),
    path('store/<int:pre_questions>/<int:post_questions>/', views.StoreView.as_view(), name='store'),
    path('delete/<int:id_metadata>/', views.DeleteView.as_view(), name='delete'),
    path('preview/<int:id_metadata>/', views.PreviewView.as_view(), name='preview'),
    path('edit_microcontent/<int:id_metadata>/', views.EditView.as_view(), name='edit_microcontent'),
    path('playlist_creation/', views.CreatePlaylistView.as_view(), name='playlist_creation'),
    path('playlist_search/', views.PlaylistSearchView.as_view(), name='playlist_search'),
    path('edit_playlist/<int:id_playlist>/', views.EditPlaylistView.as_view(), name='edit_playlist'),
    path('preview_playlist/<int:id_playlist>/', views.PreviewPlaylistView.as_view(), name='preview_playlist'),
    path('preview_keyword/<int:id_playlist>/<str:keyword>', views.PreviewKeywordView.as_view(), name='preview_keyword'),
    path('delete_playlist/<int:id_playlist>/', views.DeletePlaylistView.as_view(), name='delete_playlist'),
    path('duplicate_microcontent/<int:id_metadata>/<user>/', views.DuplicateMicrocontentView.as_view(), name='duplicate_microcontent'),
    path('duplicate_playlist/<int:id_playlist>/', views.DuplicatePlaylistView.as_view(), name='duplicate_playlist'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentsmanager/urls.py
from django.urls import path

from . import views

app_name = 'studentsmanager'

urlpatterns = [
    path('user_data/', views.UserDataView.as_view(), name='user_data'),
    path('edit_user_data/<int:id>', views.EditUserDataView.as_view(), name='edit_user_data'),
    path('password_change/', views.change_password, name='password_change'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignUpActive.as_view(), name='signup'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('courses_list', views.CoursesListView.as_view(), name='courses_list'),
    path('enroll_in_course/<int:course_id>', views.EnrollView.as_view(), name='enroll_in_course'),
    path('choose_itinerary/<int:course_id>', views.ChooseItineraryView.as_view(), name='choose_itinerary'),
    path('send_notification/<int:course_id>/<user>/<str:text>', views.sendNotificationView.as_view(),name='send_notification'),
    path('my_courses', views.MyCoursesView.as_view(), name='my_courses'),
    path('try_playlist/<int:course_id>', views.TryPlaylistView.as_view(), name='try_playlist'),
    path('restart_playlist/<int:course_id>', views.restartCourse.as_view(), name='restart_playlist'),
    path('course_keyword/<int:course_id>', views.CourseKeywordView.as_view(), name='course_keyword'),
    path('get_state_record/<user>/<course>/', views.get_state_record, name='get_state_record'),
    path('get_microcontent_state/<user>/<microcontent>', views.get_microcontent_state, name='get_microcontent_state'),
    path('course_microcontents/<int:course_id>/<str:keyword>', views.CourseMicrocontentsView.as_view(), name='course_microcontents'),
    path('try_microcontent/<int:mc_id>', views.TryMicrocontentView.as_view(), name='try_microcontent'),
    path('try_microcontent/<str:mc_id>', views.TryMicrocontentView.as_view(), name='try_microcontent'),
    path('get_courses/<user>/', views.get_courses, name='get_courses'),
    path('check_alexa/<user>/<str:alexa_id>/', views.check_alexa, name='check_alexa'),
    path('register_alexa/<user>/<str:alexa_id>/<str:birthday>', views.register_alexa, name='register_alexa'),
    path('get_microcontent/<user>/<str:microcontent_id>/', views.get_microcontent, name='get_microcontent'),
    path('get_result/<user>/<str:microcontent_id>/<str:position>/<str:answers>/', views.get_result, name='get_result'),
    path('telegram/execute_task/', views.periodic_task, name="periodic_task"),
    path('telegram/<str:telegram_id>/get_state_record/<course>/', views.get_state_record_telegram, name='get_state_record_telegram'),
    path('telegram/<str:telegram_id>/get_states_keyword/',views.get_states_keyword, name='get_states_keyword'),
    path('telegram/<str:telegram_id>/get_next_microcontent/<course_id>', views.get_next_telegram, name='get_next_telegram'),
    path('telegram/<str:telegram_id>/restart/<course_id>/', views.telegram_restart, name='restart'),
    path('telegram/<str:telegram_id>/get_microcontent/<str:keyword>/<str:level>/', views.get_microcontent_telegram, name='get_microcontent_telegram'),
    path('telegram/<str:telegram_id>/get_result/<str:microcontent_id>/<str:position>/<str:answers>/', views.get_result_telegram, name='get_result_telegram'),
    path('telegram/<str:telegram_id>/get_keywords/', views.get_keywords, name="get_keywords"),
    path('telegram/<str:telegram_id>/activate_notifications/', views.activate_notifications, name="activate_notifications"),
    path('telegram/<str:telegram_id>/comment/<str:comment>/', views.get_comments, name='get_comments')
]

studentsmanager/views.py
from ast import keyword
from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm, AuthenticationForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import PasswordContextMixin, SuccessURLAllowedHostsMixin, \
    INTERNAL_RESET_SESSION_TOKEN, LoginView
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.http.response import Http404
from django.shortcuts import redirect, resolve_url
from django.utils.decorators import method_decorator
from django.utils.http import url_has_allowed_host_and_scheme
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import (
    REDIRECT_FIELD_NAME, get_user_model, login as auth_login,
    logout as auth_logout, update_session_auth_hash,
    authenticate)
from django.utils.datastructures import MultiValueDictKeyError
from importlib_metadata import metadata
from rest_framework import viewsets
from datetime import date, timedelta


from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
#añadida tras error en signup
from django.core.mail import send_mail
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views import generic
from django.utils import timezone
from django.forms.models import model_to_dict
from datetime import datetime
from dateutil.relativedelta import relativedelta
from studentsmanager.forms import UserCreateForm
from studentsmanager.serializers import UserSerializer
from studentsmanager.models import Keywords_State, Student, Trace, State, Comments

from authoringtool.models import Playlist, SortedMicrocontent, MicroContent

import json
import operator, random, requests

UserModel = get_user_model()

# API classes
class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = User.objects.all().order_by('-date_joined')
    serializer_class = UserSerializer
#

#VISUALIZACION DE PANTALLA DE INICIO
class HomeView(TemplateView):

    def get(self, request, *args, **kwargs):
        return render(request, 'studentsmanager/user_page.html')

#COMPROBACION DE DATOS --> AL EDITAR SE ENVIA A EditUserDataView
class UserDataView(TemplateView):
    def get(self, request, *args, **kwargs):
        student = Student.objects.filter(id=self.request.user.id).get()
        template_name = 'studentsmanager/user_data_show_and_edit.html'
        return render(request, template_name, {'students':student})

#PANTALLA DE REGISTRO/LOGIN
class LoginView(SuccessURLAllowedHostsMixin, FormView):
    """
        Display the login form and handle the login action.
        """
    form_class = AuthenticationForm
    authentication_form = None
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = 'registration/login.html'
    redirect_authenticated_user = False
    extra_context = None
    
    @method_decorator(sensitive_post_parameters())
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if self.redirect_authenticated_user and self.request.user.is_authenticated:
            redirect_to = self.get_success_url()
            if redirect_to == self.request.path:
                raise ValueError(
                    "Redirection loop for authenticated user detected. Check that "
                    "your LOGIN_REDIRECT_URL doesn't point to a login page."
                )
            return HttpResponseRedirect(redirect_to)
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        url = self.get_redirect_url()
        return url or resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_redirect_url(self):
        """Return the user-originating redirect URL if it's safe."""
        redirect_to = self.request.POST.get(
            self.redirect_field_name,
            self.request.GET.get(self.redirect_field_name, '')
        )
        url_is_safe = url_has_allowed_host_and_scheme(
            url=redirect_to,
            allowed_hosts=self.get_success_url_allowed_hosts(),
            require_https=self.request.is_secure(),
        )
        return redirect_to if url_is_safe else ''

    def get_form_class(self):
        return self.authentication_form or self.form_class

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        """Security check complete. Log the user in."""
        auth_login(self.request, form.get_user())
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_site = get_current_site(self.request)
        context.update({
            self.redirect_field_name: self.get_redirect_url(),
            'site': current_site,
            'site_name': current_site.name,
            **(self.extra_context or {})
        })
        return context

#MODIFICACION DE CONTRASEÑAS
class PasswordResetView(PasswordContextMixin, FormView):
    email_template_name = 'registration/password_reset_email.html'
    extra_email_context = None
    form_class = PasswordResetForm
    from_email = None
    html_email_template_name = None
    subject_template_name = 'registration/password_reset_subject.txt'
    success_url = reverse_lazy('password_reset_done')
    template_name = 'registration/password_reset_form.html'
    title = ('Password reset')
    token_generator = default_token_generator

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        opts = {
            'use_https': self.request.is_secure(),
            'token_generator': self.token_generator,
            'from_email': self.from_email,
            'email_template_name': self.email_template_name,
            'subject_template_name': self.subject_template_name,
            'request': self.request,
            'html_email_template_name': self.html_email_template_name,
            'extra_email_context': self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


class PasswordResetConfirmView(PasswordContextMixin, FormView):
    form_class = SetPasswordForm
    post_reset_login = True
    post_reset_login_backend = None
    success_url = reverse_lazy('password_reset_complete')
    template_name = 'registration/password_reset_confirm.html'
    title = ('Enter new password')
    token_generator = default_token_generator

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        assert 'uidb64' in kwargs and 'token' in kwargs

        self.validlink = False
        self.user = self.get_user(kwargs['uidb64'])

        if self.user is not None:
            token = kwargs['token']
            if token == 'set-password': #INTERNAL_RESET_URL_TOKEN:
                session_token = self.request.session.get(INTERNAL_RESET_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                if self.token_generator.check_token(self.user, token):
                    # Store the token in the session and redirect to the
                    # password reset form at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_RESET_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(token, 'set-password')
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())

    def get_user(self, uidb64):
        try:
            # urlsafe_base64_decode() decodes to bytestring
            uid = urlsafe_base64_decode(uidb64) #.decode()
            user = UserModel._default_manager.get(pk=uid)
        except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist, ValidationError):
            user = None
        return user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.user
        return kwargs

    def form_valid(self, form):
        user = form.save()
        if form.is_valid():
            username = self.user
            password = form.cleaned_data['new_password1']
            u = User.objects.get(username=username)
            u.set_password(password)
            u.save()
        del self.request.session[INTERNAL_RESET_SESSION_TOKEN]
        if self.post_reset_login:
            auth_login(self.request, user, self.post_reset_login_backend)
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.validlink:
            context['validlink'] = True
        else:

studentsmanager/templates/studentsmanager/courses_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Enroll</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authoring_tool_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">
    <script>
        function seleccionar(sel, desel) {
            for (var i = 1; i < desel+1; i++) { 
                document.getElementById("option" + i).style.color = '#6f6cde';
                document.getElementById("option" + i).style.boxShadow = '-6px -6px 10px rgba(255, 255, 255, 0.8), 6px 6px 10px rgba(0, 0, 0, 0.2)';
            }
            document.getElementById("option" + sel).style.color = '#6BE579';
            document.getElementById("option" + sel).style.boxShadow = 'inset -4px -4px 8px rgba(255, 255, 255, 0.5), inset 8px 8px 16px rgba(0, 0, 0, 0.1)';
        }

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 0; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("td")[n];
                    y = rows[i + 1].getElementsByTagName("td")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerText.toLowerCase() > y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerText.toLowerCase() < y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>

    <script>
        function promptFunction(list_id) {
            let text;
            let notification = prompt("Introduce the text to send:", "Has sido dado de alta en el curso");
            if (person == null || person == "") {
                text = "User cancelled the prompt";
            } else {
                text = person
            }
            document.getElementById("demo").innerHTML=text
            window.open("http://193.146.210.19:8080/accounts/send_notification/33/saraalumna/33")


        }
    </script>
    
    <h1>Enroll in a course</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>
    <div class="table-wrapper">
        <table class="fl-table" id="myTable">
            <thead>
            <tr>
                <th onclick="sortTable(0)">Title</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% for list in playlists %}
                    <tr>
                        <td>{{ list.name }}</td>
                        <td>
                        {% csrf_token %}
                            <div class="table_button">
                                <a id="view_button" class="po view" title="View Microcontents List" href="{% url 'authoringtool:preview_playlist' list.id %}">
                                <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>

                                <a id="enroll_button" class="po enroll" title="Enroll Course" href="{% url 'studentsmanager:choose_itinerary' list.id %}">
                                <i id="enroll" class="fa fa-plus" aria-hidden="true"></i></a>
                                
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            <tbody>
        </table>
    </div>
<body>

studentsmanager/templates/studentsmanager/itinerary_creation.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Itinerary edition</title>
    <link rel="stylesheet" type="text/css" href="{% static 'itinerary.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom" onbeforeprint="isChecked()">
<form name="myform" action="{% url 'studentsmanager:choose_itinerary' playlist.id %}" method="post" enctype="multipart/form-data">
{% csrf_token %}

  <header>
    <h1 class="top-content"><a id="home_button" class="po home" title="Go back to courses list" href="{% url 'studentsmanager:courses_list' %}"><i id="home" class="fa fa-reply" aria-hidden="true"></i></a></h1>
  </header>

  <h2>{{ playlist.name}} </h2>
  <input type="hidden" id="microcontents_in" name="microcontents_in" value="{{ microcontents_in }}">
  <fieldset>
    <legend>Select your itinerary</legend>
    {% for kw in microcontents %}
      <label class="container">
        <input type="checkbox" name="itinerary" value="{{kw}}">{{ kw }}</option><br>
        <span class="checkmark"></span>
      </label>
    {% endfor %}
  <br><br>
  </fieldset>
  <br><br>
  <input class="button" type="submit" value="Save"> 
  </form>
</body>
</html>

<script>
function isChecked() {
  var checkboxes = document.getElementsByName('itinerary');
  var keywords_in = document.getElementById("microcontents_in").value;
  for (var i = 1; i <= checkboxes.length; i++) {
    for (var j = 1; j <=keywords_in.length; j++) {
      if (checkboxes[i].value == keywords_in[j]) {
        checkboxes[i].checked = true;
      }
      checkboxes[i].setAttribute('value', 'order_' + i);
    }
  }
}

</script>

studentsmanager/templates/studentsmanager/my_courses.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Enroll</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authoring_tool_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">
    <script>

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 0; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("td")[n];
                    y = rows[i + 1].getElementsByTagName("td")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerText.toLowerCase() > y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerText.toLowerCase() < y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
    
    <h1>My courses</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>

    <div class="table-wrapper">
        <table class="fl-table" id="myTable">
            <thead>
            <tr>
                <th onclick="sortTable(0)">Title</th>
                <th>Options</th>
            </tr>
            </thead>
            <tbody>
            {% for course in courses %}
                    <tr>
                        <td>{{ course.name }}</td>
                        <td>
                        {% csrf_token %}
                            <div class="table_button">
                                <a id="play_button" class="po play" title="Play Playlist" href="{% url 'studentsmanager:try_playlist' course.id %}">
                                <i id="play" class="fa fa-play" aria-hidden="true"></i></a>
                                <a id="view_button" class="po view" title="View Keywords List" href="{% url 'studentsmanager:course_keyword' course.id %}">
                                <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>
                                <a id="undo_button" class="po undo" title="Restart Playlist" href="{% url 'studentsmanager:restart_playlist' course.id %}">
                                <i id="undo" class="fa fa-undo" aria-hidden="true"></i></a>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
            <tbody>
        </table>
    </div>
<body>

studentsmanager/templates/studentsmanager/user_data.html
{% load static %}
<!DOCTYPE html>
<style>
</style>
<html>
	<head>
		<title>User data</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'demo.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'sky-forms.css' %}">
        	<link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}"/>

	</head>
	<body class="bg-study">
		<div class="body body-s">

			<form method="post" class="sky-form">
                {% csrf_token %}
				<header>User data<a id="id_back_button" class="authoringtool:menu' %}">Home</a></header>
				<fieldset>
                    {{ form.errors }}
					<section>
                           - Username: {{ user.username }}
					</section>

					<section>
						- First name: {{ user.first_name }}
					</section>

					<section>
						- Last name: {{ user.last_name }}
					</section>

					<section>
						- Email: {{ user.email }}
					</section>

					<section>
						-Telegram ID: {{ students.telegram_id }}
					</section>
				</fieldset>


				<footer>
                    <a class="button" href="{% url 'studentsmanager:edit_user_data' user.id %}" style="background-color: green;">Edit data</a>
                    <a class="button" href="{% url 'studentsmanager:password_change' %}" style="background-color: green;">Password change</a>
                </footer>
			</form>

		</div>


	</body>
</html>