aprendeii/urls.py
from django.contrib import admin
from django.urls import path, include
import studentsmanager.views as studentsmanager_views
#import authoringtool.views as authoringtool_views

# API
#from rest_framework import routers
#from rest_framework.urlpatterns import format_suffix_patterns

#router = routers.DefaultRouter()
#router.register(r'units', mc_views.UnitViewSet)
#router.register(r'users', usersmanager_views.UserViewSet)
# router.register('^units/{unit}/$', mc_views.unit_detail, basename="unit-detail")

urlpatterns = [
    path('', studentsmanager_views.LoginView.as_view(), name='login'),
    #path('api/', include(router.urls)),
    #path('units/', authoringtool_views.UnitList.as_view()),
    #path('units/<str:unit>/', authoringtool_views.UnitDetail.as_view()),
    path('authoringtool/', include('authoringtool.urls')),
    path('admin/', admin.site.urls),
    path('user_page/', studentsmanager_views.HomeView.as_view(), name='user_page'),
    path('accounts/', include('studentsmanager.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('usersmanager/', include('usersmanager.urls')),
    path('ebisu/', include('ebisu_api.urls')),
    #path('authoringtool', authoringtool_views.microcontent, name='authoringtool'),
]

authoringtool/urls.py
from django.urls import path

from . import views
from studentsmanager import views as user_views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'authoringtool'

urlpatterns = [
    path('', user_views.HomeView.as_view(), name='menu'),
    path('newMicroContent/<int:preq>/<int:media>/<int:postq>', views.MicroContentCreationView.as_view(), name='microcontent_creation'), 
    path('microcontent_search/', views.MicroContentSearchView.as_view(), name='microcontent_search'),
    path('createSelection/', views.CreateSelectionView.as_view(), name='create_selection'),
    path('store/<int:pre_questions>/<int:post_questions>/', views.StoreView.as_view(), name='store'),
    path('delete/<int:id_metadata>/', views.DeleteView.as_view(), name='delete'),
    path('preview/<int:id_metadata>/', views.PreviewView.as_view(), name='preview'),
    path('edit_microcontent/<int:id_metadata>/', views.EditView.as_view(), name='edit_microcontent'),
    path('playlist_creation/', views.CreatePlaylistView.as_view(), name='playlist_creation'),
    path('playlist_search/', views.PlaylistSearchView.as_view(), name='playlist_search'),
    path('edit_playlist/<int:id_playlist>/', views.EditPlaylistView.as_view(), name='edit_playlist'),
    path('preview_playlist/<int:id_playlist>/', views.PreviewPlaylistView.as_view(), name='preview_playlist'),
    path('preview_keyword/<int:id_playlist>/<str:keyword>', views.PreviewKeywordView.as_view(), name='preview_keyword'),
    path('delete_playlist/<int:id_playlist>/', views.DeletePlaylistView.as_view(), name='delete_playlist'),
    path('duplicate_microcontent/<int:id_metadata>/<user>/', views.DuplicateMicrocontentView.as_view(), name='duplicate_microcontent'),
    path('duplicate_playlist/<int:id_playlist>/', views.DuplicatePlaylistView.as_view(), name='duplicate_playlist'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studentsmanager/urls.py
from django.urls import path

from . import views

app_name = 'studentsmanager'

urlpatterns = [
    path('user_data/', views.UserDataView.as_view(), name='user_data'),
    path('edit_user_data/<int:id>', views.EditUserDataView.as_view(), name='edit_user_data'),
    path('password_change/', views.change_password, name='password_change'),
    path('login', views.LoginView.as_view(), name='login'),
    path('signup/', views.SignUpActive.as_view(), name='signup'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('courses_list', views.CoursesListView.as_view(), name='courses_list'),
    path('enroll_in_course/<int:course_id>', views.EnrollView.as_view(), name='enroll_in_course'),
    path('choose_itinerary/<int:course_id>', views.ChooseItineraryView.as_view(), name='choose_itinerary'),
    path('send_notification/<int:course_id>/<user>/<str:text>', views.sendNotificationView.as_view(),name='send_notification'),
    path('my_courses', views.MyCoursesView.as_view(), name='my_courses'),
    path('try_playlist/<int:course_id>', views.TryPlaylistView.as_view(), name='try_playlist'),
    path('restart_playlist/<int:course_id>', views.restartCourse.as_view(), name='restart_playlist'),
    path('course_keyword/<int:course_id>', views.CourseKeywordView.as_view(), name='course_keyword'),
    path('get_state_record/<user>/<course>/', views.get_state_record, name='get_state_record'),
    path('get_microcontent_state/<user>/<microcontent>', views.get_microcontent_state, name='get_microcontent_state'),
    path('course_microcontents/<int:course_id>/<str:keyword>', views.CourseMicrocontentsView.as_view(), name='course_microcontents'),
    path('try_microcontent/<int:mc_id>', views.TryMicrocontentView.as_view(), name='try_microcontent'),
    path('try_microcontent/<str:mc_id>', views.TryMicrocontentView.as_view(), name='try_microcontent'),
    path('get_courses/<user>/', views.get_courses, name='get_courses'),
    path('check_alexa/<user>/<str:alexa_id>/', views.check_alexa, name='check_alexa'),
    path('register_alexa/<user>/<str:alexa_id>/<str:birthday>', views.register_alexa, name='register_alexa'),
    path('get_microcontent/<user>/<str:microcontent_id>/', views.get_microcontent, name='get_microcontent'),
    path('get_result/<user>/<str:microcontent_id>/<str:position>/<str:answers>/', views.get_result, name='get_result'),
    path('telegram/execute_task/', views.periodic_task, name="periodic_task"),
    path('telegram/<str:telegram_id>/get_state_record/<course>/', views.get_state_record_telegram, name='get_state_record_telegram'),
    path('telegram/<str:telegram_id>/get_states_keyword/',views.get_states_keyword, name='get_states_keyword'),
    path('telegram/<str:telegram_id>/get_next_microcontent/<course_id>', views.get_next_telegram, name='get_next_telegram'),
    path('telegram/<str:telegram_id>/restart/<course_id>/', views.telegram_restart, name='restart'),
    path('telegram/<str:telegram_id>/get_microcontent/<str:keyword>/<str:level>/', views.get_microcontent_telegram, name='get_microcontent_telegram'),
    path('telegram/<str:telegram_id>/get_result/<str:microcontent_id>/<str:position>/<str:answers>/', views.get_result_telegram, name='get_result_telegram'),
    path('telegram/<str:telegram_id>/get_keywords/', views.get_keywords, name="get_keywords"),
    path('telegram/<str:telegram_id>/activate_notifications/', views.activate_notifications, name="activate_notifications"),
    path('telegram/<str:telegram_id>/comment/<str:comment>/', views.get_comments, name='get_comments')
]

usersmanager/urls.py
from django.urls import path

from . import views

app_name = 'usersmanager'

urlpatterns = [
    path('user_data/', views.UserDataView.as_view(), name='user_data'),
    path('edit_user_data/<int:id>', views.EditUserDataView.as_view(), name='edit_user_data'),
    path('password_change/', views.change_password, name='password_change'),
    path('login/', views.LoginView.as_view(), name='login_as_teacher'),
    path('signup/', views.SignUp.as_view(), name='signup_as_teacher'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    path('students_list_pl/<playlist_id>', views.StudentsListViewPlaylist.as_view(), name='students_list_playlist'),
    path('students_list/<playlist_id>/<mc_id>', views.StudentsListView.as_view(), name='students_list'),
    path('export_all/<user>/<playlist_id>', views.export_all, name='export_all'),
    path('view_traces_all/<user>/<playlist_id>', views.ViewGeneralTraces.as_view(), name='view_all_traces'),
    path('export/<user>/<mc_id>', views.export, name='export'),
    path('view_comments/', views.viewCommentsView.as_view(), name='viewcomments'),
    path('view_comments/<user>', views.viewCommentsperStudentView.as_view(), name='view_comments_per_student'),
    path('view_traces/<user>/<mc_id>', views.ViewTracesView.as_view(), name='view_traces')
]

usersmanager/models.py
from django.db import models

# Create your models here.

usersmanager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Email address'}))
    first_name = forms.CharField(required=True, max_length=150, widget=forms.TextInput(attrs={'placeholder': 'First name'}))
    last_name = forms.CharField(required=True, max_length=150, widget=forms.TextInput(attrs={'placeholder': 'Last name'}))
    username = forms.CharField(required=True, max_length=150, widget=forms.TextInput(attrs={'placeholder': 'Username'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': 'Password confirmation'})

usersmanager/templates/usersmanager/students_enrolled_playlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Students list</title>
    <link rel="stylesheet" type="text/css" href="{% static 'authoring_tool_style.css' %}">
    <link rel="icon" type="image/png" href="{% static 'images/icons/book.png' %}" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>

<body class="bottom">
    
    <h1>Students in {{ course }}</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Go back to courses list" onClick="javascript:history.go(-1);" style="cursor:pointer;"><i id="home" class="fa fa-reply" aria-hidden="true"></i></a></h1>


    <br>

    <div class="table-wrapper">
        <table class="fl-table" id="myTable">
            <thead>
            <tr>
                <th onclick="sortTable(0)">First Name</th>
                <th onclick="sortTable(1)">Last Name</th>
                <th onclick="sortTable(2)">Email</th>
                <th onclick="sortTable(3)">Last Log In</th>
                <th>Options</th>
                <th>Send message</th>
            </tr>
            </thead>
            <tbody>
            {% for st in students %}
                    <tr>
                        <td>{{ st.first_name }}</td>
                        <td>{{ st.last_name}}</td>
                        <td>{{ st.email }}</td>
                        <td>{{ st.last_login }}</td>
                        <td>
                        {% csrf_token %}
                            <div class="table_button">
                                <a id="view_button" class="po view" title="View traces" href="{% url 'usersmanager:view_all_traces' st.username course %}">
                                <i id="view" class="fa fa-eye" aria-hidden="true"></i></a>

                                <a id="download_button" class="po download" title="Download csv" href="{% url 'usersmanager:export_all' st.username course %}">
                                <i id="download" class="fa fa-cloud-download" aria-hidden="true"></i></a>

                                <a id="comments_button" class="po comments" title="View Comments" href="{% url 'usersmanager:view_comments_per_student' st.username %}">
                                <i id="comments" class="fa fa-comments" aria-hidden="true"></i></a>
                            </div>
                        </td>
                        <td>
                            <div>
                                <form name="myform" action="{% url 'studentsmanager:send_notification' 35 st.username 35%}" method="post" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <input type="text" id="message" name="message" value="Has sido dado de alta en el curso. Para empezar dime /siguiente"/>
                                    <input class="button-create" type="submit" value="Send">
                                </form>
                            </div>

                        </td>
                    </tr>
                {% endfor %}
            <tbody>
        </table>
    </div>
    <script>

        function sortTable(n) {
            var table, rows, switching, i, x, y, shouldSwitch, dir, switchcount = 0;
            table = document.getElementById("myTable");
            switching = true;
            //Set the sorting direction to ascending:
            dir = "asc";
            /*Make a loop that will continue until
            no switching has been done:*/
            while (switching) {
                //start by saying: no switching is done:
                switching = false;
                rows = table.rows;
                /*Loop through all table rows (except the
                first, which contains table headers):*/
                for (i = 0; i < (rows.length - 1); i++) {
                    //start by saying there should be no switching:
                    shouldSwitch = false;
                    /*Get the two elements you want to compare,
                    one from current row and one from the next:*/
                    x = rows[i].getElementsByTagName("td")[n];
                    y = rows[i + 1].getElementsByTagName("td")[n];
                    /*check if the two rows should switch place,
                    based on the direction, asc or desc:*/
                    if (dir == "asc") {
                        if (x.innerText.toLowerCase() > y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    } else if (dir == "desc") {
                        if (x.innerText.toLowerCase() < y.innerText.toLowerCase()) {
                            //if so, mark as a switch and break the loop:
                            shouldSwitch = true;
                            break;
                        }
                    }
                }
                if (shouldSwitch) {
                    /*If a switch has been marked, make the switch
                    and mark that a switch has been done:*/
                    rows[i].parentNode.insertBefore(rows[i + 1], rows[i]);
                    switching = true;
                    //Each time a switch is done, increase this count by 1:
                    switchcount++;
                } else {
                    /*If no switching has been done AND the direction is "asc",
                    set the direction to "desc" and run the while loop again.*/
                    if (switchcount == 0 && dir == "asc") {
                        dir = "desc";
                        switching = true;
                    }
                }
            }
        }
    </script>
<body>

usersmanager/templates/usersmanager/user_data_and_edit.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Log in</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'user_data_style.css' %}">
        <link rel="icon" type="image/png" href="{% static 'images/icons/home.ico' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	</head>
    
    <body>
    <h1>User data</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>
    
        <div class ="log_in_container_wrapper">
            <div class="container">
                <div class="overlay" id="overlay">
                    <div class="sign-in" id="sign-in">
                        <h1>Something Wrong?</h1>
                        <p>Don't worry, you can easily change you personal information</p>
                        <button class="switch-button" id="slide-right-button">Edit data</button>
                    </div>
                    <div class="sign-up" id="sign-up">
                        <h1>Everything Ok?</h1>
                        <p>If everything is ok you can go back and see your data</p>
                        <button class="switch-button" id="slide-left-button">View Data</button>
                    </div>
                </div>
                <div class="form">
                    <div class="sign-in" id="sign-in-info">
                        <h1>Edit Data</h1>
                        <form id="sign-in-form" method="post" action="{% url 'usersmanager:edit_user_data' user.id %}">
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            
                            <input name="userName" type="text" placeholder="Username" value="{{ user.username }}" autofocus="" required="" id="id_username">
                            <input name="firstName" type="text" placeholder="First Name" value="{{ user.first_name }}" autofocus="" required="" id="id_username">
                            <input name="lastName" type="text" placeholder="Last Name" value="{{ user.last_name }}" autofocus="" required="" id="id_username">
                            <input name="email" type="text" placeholder="Email" value="{{ user.email }}" autofocus="" required="" id="id_username">
                           
                            <button class="control-button in">Save</button>

                            
                        </form>
                    </div>

                    <div class="sign-up" id="sign-up-info">
                        <h1>Your data</h1><br><br>
                        <form id="sign-up-form" method="post" action="{% url 'studentsmanager:signup' %}">
                            {% csrf_token %}
                            {{ form.errors }}
                            
                            <h2 class="home-title">
                                Username: <span>{{ user.username }}</span>
                            </h2>
                            <h2 class="home-title">
                                First Name: <span>{{ user.first_name }}</span>
                            </h2>
                            <h2 class="home-title">
                                Last Name: <span>{{ user.last_name }}</span>
                            </h2>
                            <h2 class="home-title">
                                Email: <span>{{ user.email }}</span>
                            </h2>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <script>
            var overlay = document.getElementById("overlay");

            // Buttons to 'switch' the page
            var openSignUpButton = document.getElementById("slide-left-button");
            var openSignInButton = document.getElementById("slide-right-button");

            // The sidebars
            var leftText = document.getElementById("sign-in");
            var rightText = document.getElementById("sign-up");

            // The forms
            var accountForm = document.getElementById("sign-in-info")
            var signinForm = document.getElementById("sign-up-info");

            // Open the Sign Up page
            openSignUp = () =>{
            // Remove classes so that animations can restart on the next 'switch'
            leftText.classList.remove("overlay-text-left-animation-out");
            overlay.classList.remove("open-sign-in");
            rightText.classList.remove("overlay-text-right-animation");
            // Add classes for animations
            accountForm.className += " form-left-slide-out"
            rightText.className += " overlay-text-right-animation-out";
            overlay.className += " open-sign-up";
            leftText.className += " overlay-text-left-animation";
            // hide the sign up form once it is out of view
            setTimeout(function(){
                accountForm.classList.remove("form-left-slide-in");
                accountForm.style.display = "none";
                accountForm.classList.remove("form-left-slide-out");
            }, 700);
            // display the sign in form once the overlay begins moving right
            setTimeout(function(){
                signinForm.style.display = "flex";
                signinForm.classList += " form-right-slide-in";
            }, 200);
            }

            // Open the Sign In page
            openSignIn = () =>{
            // Remove classes so that animations can restart on the next 'switch'
            leftText.classList.remove("overlay-text-left-animation");
            overlay.classList.remove("open-sign-up");
            rightText.classList.remove("overlay-text-right-animation-out");
            // Add classes for animations
            signinForm.classList += " form-right-slide-out";
            leftText.className += " overlay-text-left-animation-out";
            overlay.className += " open-sign-in";
            rightText.className += " overlay-text-right-animation";
            // hide the sign in form once it is out of view
            setTimeout(function(){
                signinForm.classList.remove("form-right-slide-in")
                signinForm.style.display = "none";
                signinForm.classList.remove("form-right-slide-out")
            },700);
            // display the sign up form once the overlay begins moving left
            setTimeout(function(){
                accountForm.style.display = "flex";
                accountForm.classList += " form-left-slide-in";
            },200);
            }

            // When a 'switch' button is pressed, switch page
            openSignUpButton.addEventListener("click", openSignUp, false);
            openSignInButton.addEventListener("click", openSignIn, false);
        </script>
    </body>
</html>

usersmanager/templates/usersmanager/user_data_show_and_edit.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<title>Log in</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
        <link rel="stylesheet" type="text/css" href="{% static 'user_data_style.css' %}">
        <link rel="icon" type="image/png" href="{% static 'images/icons/home.ico' %}"/>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	</head>
    
    <body>
    <h1>User data</h1>
    <h1 class="top-content"><a id="home_button" class="po home" title="Home" href="{% url 'authoringtool:menu' %}"><i id="home" class="fa fa-home" aria-hidden="true"></i></a></h1>
    
        <div class ="log_in_container_wrapper">
            <div class="container">
                <div class="overlay" id="overlay">
                    <div class="sign-in" id="sign-in">
                        <h1>Something Wrong?</h1>
                        <p>Don't worry, you can easily change you personal information</p>
                        <button class="switch-button" id="slide-right-button">Edit data</button>
                    </div>
                    <div class="sign-up" id="sign-up">
                        <h1>Everything Ok?</h1>
                        <p>If everything is ok you can go back and see your data</p>
                        <button class="switch-button" id="slide-left-button">View Data</button>
                    </div>
                </div>
                <div class="form">
                    <div class="sign-in" id="sign-in-info">
                        <h1>Edit Data</h1>
                        <form id="sign-in-form" method="post" action="{% url 'usersmanager:edit_user_data' user.id %}">
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            <strong>{{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        <strong>{{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            
                            <input name="userName" type="text" placeholder="Username" value="{{ user.username }}" autofocus="" required="" id="id_username">
                            <input name="firstName" type="text" placeholder="First Name" value="{{ user.first_name }}" autofocus="" required="" id="id_username">
                            <input name="lastName" type="text" placeholder="Last Name" value="{{ user.last_name }}" autofocus="" required="" id="id_username">
                            <input name="email" type="text" placeholder="Email" value="{{ user.email }}" autofocus="" required="" id="id_username">
                           
                            <button class="control-button in">Save</button>

                            
                        </form>
                    </div>

                    <div class="sign-up" id="sign-up-info">
                        <h1>Your data</h1><br><br>
                        <form id="sign-up-form" method="post" action="{% url 'studentsmanager:signup' %}">
                            {% csrf_token %}
                            {{ form.errors }}
                            
                            <h2 class="home-title">
                                Username: <span>{{ user.username }}</span>
                            </h2>
                            <h2 class="home-title">
                                First Name: <span>{{ user.first_name }}</span>
                            </h2>
                            <h2 class="home-title">
                                Last Name: <span>{{ user.last_name }}</span>
                            </h2>
                            <h2 class="home-title">
                                Email: <span>{{ user.email }}</span>
                            </h2>
                        </form>
                    </div>
                </div>
            </div>
        </div>


        <script>
            var overlay = document.getElementById("overlay");

            // Buttons to 'switch' the page
            var openSignUpButton = document.getElementById("slide-left-button");
            var openSignInButton = document.getElementById("slide-right-button");

            // The sidebars
            var leftText = document.getElementById("sign-in");
            var rightText = document.getElementById("sign-up");

            // The forms
            var accountForm = document.getElementById("sign-in-info")
            var signinForm = document.getElementById("sign-up-info");

            // Open the Sign Up page
            openSignUp = () =>{
            // Remove classes so that animations can restart on the next 'switch'
            leftText.classList.remove("overlay-text-left-animation-out");
            overlay.classList.remove("open-sign-in");
            rightText.classList.remove("overlay-text-right-animation");
            // Add classes for animations
            accountForm.className += " form-left-slide-out"
            rightText.className += " overlay-text-right-animation-out";
            overlay.className += " open-sign-up";
            leftText.className += " overlay-text-left-animation";
            // hide the sign up form once it is out of view
            setTimeout(function(){
                accountForm.classList.remove("form-left-slide-in");
                accountForm.style.display = "none";
                accountForm.classList.remove("form-left-slide-out");
            }, 700);
            // display the sign in form once the overlay begins moving right
            setTimeout(function(){
                signinForm.style.display = "flex";
                signinForm.classList += " form-right-slide-in";
            }, 200);
            }

            // Open the Sign In page
            openSignIn = () =>{
            // Remove classes so that animations can restart on the next 'switch'
            leftText.classList.remove("overlay-text-left-animation");
            overlay.classList.remove("open-sign-up");
            rightText.classList.remove("overlay-text-right-animation-out");
            // Add classes for animations
            signinForm.classList += " form-right-slide-out";
            leftText.className += " overlay-text-left-animation-out";
            overlay.className += " open-sign-in";
            rightText.className += " overlay-text-right-animation";
            // hide the sign in form once it is out of view
            setTimeout(function(){
                signinForm.classList.remove("form-right-slide-in")
                signinForm.style.display = "none";
                signinForm.classList.remove("form-right-slide-out")
            },700);
            // display the sign up form once the overlay begins moving left
            setTimeout(function(){
                accountForm.style.display = "flex";
                accountForm.classList += " form-left-slide-in";
            },200);
            }

            // When a 'switch' button is pressed, switch page
            openSignUpButton.addEventListener("click", openSignUp, false);
            openSignInButton.addEventListener("click", openSignIn, false);
        </script>
    </body>
</html>